### ISSUE TITLE
Running vendetta I get unknown option -C error

### ISSUE THREAD

**Issue by vrecan** [dpw/vendetta#6] opened 2016-02-19 21:23 UTC
Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]

**Comment by dpw** [comment] 2016-02-19 22:37
Interesting.  What version of git are you using, and on what platform?  I thought the `-C` option had been there for a long time, but maybe I'm mistaken.

**Comment by vrecan** [comment] 2016-02-19 22:40
It's the default in centos 7 I'm not at the machine right now but I believe
it was git 1.8.x

**Comment by dpw** [comment] 2016-02-19 23:10
> It's the default in centos 7 I'm not at the machine right now but I believe it was git 1.8.x

Thanks, I can reproduce on centos 7.

**Comment by dpw** [comment] 2016-02-19 23:45
I've pushed a fix - it now works for me under centos7 with git 1.8.3.1.

Thanks for raising this issue!

**Closed as completed by dpw** 2016-02-19 23:45 UTC
