### ISSUE TITLE
Bitbucket not supported

### ISSUE THREAD

**Issue by matbesancon** [dpw/vendetta#18] opened 2017-02-20 08:27 UTC
As discussed in the comments of the Bitbucket error-related commit, being able to use vendetta with the hosting service would be a great plus for us, we don't wish to switch to Github or alike.

**Comment by dpw** [comment] 2017-02-20 22:41
It looks like it should be possible to reproduce the `go get` behaviour for git repos on BitBucket. But to help with implementing this feature, could you give me an example of an import path that should be supported? BitBucket does not seem to make it easy to browse public projects.

**Comment by dpw** [comment] 2017-02-26 00:38
I've made a commit to address this.  Please check whether it works for you, and close this issue if it does.

**Comment by dpw** [comment] 2017-03-12 21:26
No response, so closing.  Please re-open if it still doesn't meet your need here.

**Closed as completed by dpw** 2017-03-12 21:26 UTC
